# Generated by Django 4.1.7 on 2023-04-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('create_at', models.DateTimeField()),
            ],
        ),
    ]
